### ISSUE TITLE
How can I add & select subtitles?

### ISSUE THREAD

**Issue by BROUDING** [Pulimet/ExoPlayer-Wrapper#12]
I found your library really cool, working nicely.

Also I could see that I can add multiple subtitles, but how can I select one of them while video is playing??

I cannot find view files, but how can I make some dialog for this...?

**Comment by Pulimet** [comment]
Thank you. I'm sorry for the belated response, my library is not supporting subtitles, but you can get the instance of ExoPlayer and to play with it as you wish. Good luck!
