### ISSUE TITLE
i have 2 questions : remove ad and support rtmp/rtsp?

### ISSUE THREAD

**Issue by fukemy** [Pulimet/ExoPlayer-Wrapper#3]
Thanks you for great library, i have 2 questions that is same as above. Can you help?

**Comment by Pulimet** [comment]
Hi, sorry for belated response.
I'm not sure that I understand your question.
Remove ad? Which ad?
And what about rtmp/rtsp? 
I think you should ask this questions on ExoPlayer repo.
Thanks and good luck!
