### ISSUE TITLE
SRT Subtitle

### ISSUE THREAD

**Issue by muklah** [Pulimet/ExoPlayer-Wrapper#4]
Hi Alexey Korolev,
it's really interested library because I search a lot and really this is the best one that I found
but I have a question about the srt subtitle actually I tried to add subtitle to exoplayer using this code:

```
MediaSource mediaSource = new ExtractorMediaSource(Uri.parse("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"),
                mediaDataSourceFactory, extractorsFactory, null, null);
        Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP,
                null, Format.NO_VALUE, Format.NO_VALUE, "en", null);
        Uri uri = Uri.parse("http://www.storiesinflight.com/js_videosub/jellies.srt");
        MediaSource subtitleSource = new SingleSampleMediaSource(uri, mediaDataSourceFactory, textFormat, C.TIME_UNSET);

        MergingMediaSource mergedSource = new MergingMediaSource(mediaSource, subtitleSource);

        player.prepare(mergedSource);
```

but how can use it in your library if you can help please
thanks

**Comment by Pulimet** [comment]
Hi Muklah,

Thank you for your kind words.

Added subtitle support in version 2.17. 
Enjoy!

` implementation 'net.alexandroid.utils:exoplayerhelper:2.17'`

```
public static final String SAMPLE_1 = "http://cdn-fms.rbs.com.br/vod/hls_sample1_manifest.m3u8";
public static final String SUBTITLE = "http://www.storiesinflight.com/js_videosub/jellies.srt";
...   
mExoPlayerHelper = new ExoPlayerHelper.Builder(this, exoPlayerView)
        .setVideoUrls(SAMPLE_1)
        .setSubTitlesUrls(new ArrayList<>(Arrays.asList(SUBTITLE)));
```

**Comment by muklah** [comment]
Thanks man amazing work!
but the full screen button in the main activity not work if you can fix this problem everything going to be amazing

**Comment by Pulimet** [comment]
Thanks. 

There is a reason why this button is not implemented.
You have an option to implement it by yourself using the interface. 

```
mExoPlayerHelper = new ExoPlayerHelper.Builder(this, exoPlayerView)
...
.setMuteBtnVisible()
.setExoPlayerEventsListener(this)
...

@Override
public void onFullScreenBtnTap() {
    // Make your view stretched to full screen or not
}
```

Also you can follow the example here:

https://github.com/Pulimet/ExoPlayer-Wrapper/blob/master/app/src/main/java/net/alexandroid/utils/exoplayerlibrary/list/RecyclerViewAdapter.java


Good luck!
