### ISSUE TITLE
New logo for ExoPlayer-Wrapper

### ISSUE THREAD

**Issue by twingenious** [Pulimet/ExoPlayer-Wrapper#7]
hi @Pulimet, I was looking around GitHub and I found your project and I thought that you may need a new logo, a new face for him. I'm a designer happy to contribute open source projects.
so, I want to say this is totally free and you can stop the process anytime you want.
if you agree I can start with some sketches and ideas that I will show you until we found the logo that fits perfectly with this project💪.

Kind Regards.

**Comment by Pulimet** [comment]
Hi @twingenious, 

It sounds magical and I will be more than happy.

Thank you for reaching me out and paying attention to this library.

**Comment by twingenious** [comment]
![exoplayer_wrapper_logo](https://user-images.githubusercontent.com/43223329/46575298-19771980-c981-11e8-904d-3db6f0396099.png)
I've made this logo for your project, what do you think?

**Comment by Pulimet** [comment]
It looks great, but maybe it should be more like the original, but wrapping it somehow? What do you think?
ExoPlayer logo: https://cdn-images-1.medium.com/fit/c/36/36/1*T6Iewm9z1-b78nwfzQDnBg.png

BTW, where I should put it? At Readme file or some other place?

Thanks 🥇

**Comment by twingenious** [comment]
![exoplayer-wrapper](https://user-images.githubusercontent.com/43223329/46769175-e7cfbc80-ccb8-11e8-889f-47104c4aa326.png)
What do you think bro?

**Comment by Pulimet** [comment]
The right one looks good.

**Comment by twingenious** [comment]
@Pulimet  done! I've made the Pull Request. Check it!💪

**Comment by Pulimet** [comment]
Done. Thanks.
